services:
  wildfly:
    build: .
    ports:
      - "100:8080"
  db:
    image: postgres:latest
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_webapp
      PGDATA: /data/postgres
    volumes:
      - ./data:/data/postgres
  volumes:
    db: